import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { cn } from "@/utils";
import { createClient } from "@/utils/supabase/server";
import Header from "@/components/Header";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(outfit.className, "bg-bg relative")}>
        <Header />
        <main className="flex h-full min-h-screen flex-col items-center justify-center overflow-hidden bg-bg px-8 py-12 pb-24 lg:px-20 lg:py-24">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
